name: CI Back

on:
  pull_request:
    branches:
      - dev
      - main
      - feat/**
    paths:
      - backend/**

defaults:
  run:
    working-directory: backend

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'Release') == false
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: Setup java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Assign grant gradlew
        run: chmod +x gradlew

      - name: Test with gradle
        run: ./gradlew --info test

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      - name: Publish test report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
